### ISSUE TITLE
非法加载文件

### ISSUE THREAD

**Issue by 4pxzhou** [febsteam/FEBS-Cloud#23]
### 问题描述
简单描述下遇到的问题
新增模块后 启动并没有遇到什么问题，就是这个警告很扎眼

### 复现步骤
简单描述下问题复现的步骤
暂时无法重现，重新又试了几次但是没有类似的问题。

### 相关截图
提供相关截图，以协助问题分析
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (/server/resources/com/sun/xml/bind/jaxb-impl/2.3.0.1/jaxb-impl-2.3.0.1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

> issue模板，by MrBird.

**Comment by wuyouzhuguli** [comment]
你模块的问题，单这几行日志找不出原因。
