### ISSUE TITLE
seata在哪里集成啦 感觉莫看到捏

### ISSUE THREAD

**Issue by Bestbbb** [febsteam/FEBS-Cloud#25]
### 问题描述
简单描述下遇到的问题

### 复现步骤
简单描述下问题复现的步骤

### 相关截图
提供相关截图，以协助问题分析

> issue模板，by MrBird.

**Comment by wuyouzhuguli** [comment]
教程里分别讨论了tx-lcn、seata和rocketMQ分布式事务，代码里选择的是较为简单的tx-lcn。
