### ISSUE TITLE
FEBS-Server-Job启动异常

### ISSUE THREAD

**Issue by lonely521** [febsteam/FEBS-Cloud#30]
### 问题描述
在启动FEBS-Server-Job项目的时候，异常启动失败。

### 复现步骤
直接启动FEBS-Server-Job项目。
查找相关的资料“https://github.com/spring-projects/spring-boot/issues/16656”，尝试在排除以来，问题没有解决。

### 相关截图
![image](https://user-images.githubusercontent.com/10920111/92695757-853b3b80-f37b-11ea-8ca9-82f3c67b31b1.png)

> issue模板，by MrBird.

**Comment by wuyouzhuguli** [comment]
什么情况下出错，可以提供复现步骤么。

**Comment by lonely521** [comment]
根据教程文档，配置好相关变量数据库等等配置后，其它的项目都能正常启动，FebsAdminApplication、FebsAuthApplication、FebsGatewayApplication、FebsServerSystemApplication、FebsServerTestApplication、FebsTxManagerApplication均能正常启动项目，只有FebsServerJobApplication在启动的时候启动不能正常启动。在我本地环境每次启动都能复现，代码是最近全量下载的git上的代码，nacos、redis、数据库等均为vagrant虚拟机。在QQ群有提问并且@了你。可能你比较忙，没看到。

**Comment by wuyouzhuguli** [comment]
Q群里沟通吧，上午有空。
