### ISSUE TITLE
菜单路由问题

### ISSUE THREAD

**Issue by kxzhot** [febsteam/FEBS-Cloud#34]
### 问题描述
目前菜单路由是二级菜单，当再往下级添加菜单之后，菜单路由就异常了。

**Comment by wuyouzhuguli** [comment]
https://www.kancloud.cn/mrbird/spring-cloud/1264992 这里有介绍如何创建三级菜单。

**Comment by kxzhot** [comment]
噢，我没考虑前端。想着应该也用不上三级菜单，后端就返回到二级菜单就行了
