### ISSUE TITLE
访问后端API接口时，没有token会跳出一个登录的form表单，在哪里取消

### ISSUE THREAD

**Issue by mushroomlb** [febsteam/FEBS-Cloud#39]
### 问题描述
开启权限验证后，访问后端API接口时，没有token会跳出一个登录的form表单，在哪里取消

### 相关截图
提供相关截图，以协助问题分析

**Comment by wuyouzhuguli** [comment]
使用axios访问需要认证的接口，如果没有携带令牌的话，返回http状态吗是401。如果需要在没有携带令牌的情况下访问需要认证的接口，可以考虑部分接口免认证。
