### ISSUE TITLE
系统controller层的访问日志现在只有server-system中有，其他模块中添加比较麻烦，建议做成通用模块

### ISSUE THREAD

**Issue by mushroomlb** [febsteam/FEBS-Cloud#40]
### 问题描述
系统controller层的访问日志现在只有server-system中有，其他模块中添加比较麻烦，建议做成通用模块

**Comment by wuyouzhuguli** [comment]
可以自己修改为各微服务push日志到MQ，MQ将日志推给log模块，log模块入库持久化；推荐使用RocketMQ的单向消息。
